env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:jest/recommended
  - standard
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
rules: {}
